spring.application.name=training-management
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/training_management}
spring.datasource.username=${DB_USERNAME:training_app}
spring.datasource.password=${DB_PASSWORD:your_password}
spring.sql.init.mode=never
server.error.include-message=never
server.error.include-stacktrace=never
server.port=8081

